<a href="https://colab.research.google.com/github/azrasm/ml-hotel-booking-analysis/blob/main/%C4%8Ci%C5%A1%C4%87enje_dataseta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_bookings2(zaprljan).csv')
df.head()

/tmp/ipython-input-2658431861.py:1: DtypeWarning: Columns (11,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_bookings2(zaprljan).csv')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,NO,3četiri2,'15,July,2_7,1,nulica,0,2,...,No Deposit,NaN,NaN,0 mjeseci i 0 dana,TRanSIeNt,0+0.0,nemam auto :(,nula,0000,01/07/2015
1,Resort Hotel,0,737,'15,7,2_7,1,nulica,0,2,...,0,NaN,NaN,0 mjeseci i 0 dana,Transient,0+0.0,0,nula,0000,01/07/2015
2,Resort Hotel,NO,7,'15,July,2_7,1,nulica,2^0,samac,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,NO,13,'15,July,2_7,1,nulica,2^0,samac,...,No Deposit,304.0,NaN,0 mjeseci i 0 dana,trAnSiEnt,75+0.0,nemam auto :(,nula,0000,02/07/2015
4,Resort Hotel,0,14,'15,7,2_7,1,nulica,2^1,2,...,No Deposit,0o360,NaN,0 mjeseci i 0 dana,Transient,98.0,0,nedovoljan,0000,03/07/2015

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  object
 3   arrival_date_year               119390 non-null  object
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  object
 6   arrival_date_day_of_month       119390 non-null  object
 7   stays_in_weekend_nights         119390 non-null  object
 8   stays_in_week_nights            119390 non-null  object
 9   adults                          119390 non-null  object
 10  children                        119386 non-null  object
 11  babies                          119390 non-null  object
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  object
 17  previous_cancellations          119390 non-null  object
 18  previous_bookings_not_canceled  119390 non-null  object
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  object
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  object
 24  company                         6797 non-null    object
 25  days_in_waiting_list            119390 non-null  object
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  object
 28  required_car_parking_spaces     119390 non-null  object
 29  total_of_special_requests       119390 non-null  object
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: object(32)
memory usage: 29.1+ MB

In [ ]:
df.describe()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
count,119390,119390,119390,119390,119390,119390,119390,119390,119390,119390,...,119390,103050,6797,119390,119390,119390,119390,119390,119390,119390
unique,4,4,479,3,24,53,578,17,35,14,...,6,595,527,231,7475,12549,7,12,6,1804
top,City Hotel,0,0,'16,August,3_3,17,nulica,2^1,2,...,No Deposit,9.0,****,0 mjeseci i 0 dana,Transient,62.0,0,nula,0000,21/10/2015
freq,51660,36632,6345,56707,10233,3580,3647,51998,33684,89680,...,43949,19763,659,63660,59176,1966,70525,45044,39099,942

In [ ]:
df.nunique()

hotel                                 4
is_canceled                           4
lead_time                           479
arrival_date_year                     3
arrival_date_month                   24
arrival_date_week_number             53
arrival_date_day_of_month           578
stays_in_weekend_nights              17
stays_in_week_nights                 35
adults                               14
children                              5
babies                                8
meal                                  8
country                             204
market_segment                        8
distribution_channel                605
is_repeated_guest                     4
previous_cancellations               21
previous_bookings_not_canceled      105
reserved_room_type                   19
assigned_room_type                   16
booking_changes                      22
deposit_type                          6
agent                               595
company                             527
days_in_waiting_list                231
customer_type                      7475
adr                               12549
required_car_parking_spaces           7
total_of_special_requests            12
reservation_status                    6
reservation_status_date            1804
dtype: int64

**Kolona "hotel":**

In [ ]:
df["hotel"].value_counts(dropna=False)

hotel
City Hotel      51660
CH              27670
Resort Hotel    26109
RH              13951
Name: count, dtype: int64

In [ ]:
df.loc[df["hotel"] == "CH", "hotel"] = "City Hotel"

In [ ]:
df.loc[df["hotel"] == "RH", "hotel"] = "Resort Hotel"

In [ ]:
df["hotel"].value_counts(dropna=False)

hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

**Kolona "is_canceled":**

In [ ]:
df["is_canceled"].value_counts(dropna=False)

is_canceled
0      36632
NO     34476
YES    26771
1      21511
Name: count, dtype: int64

In [ ]:
df.loc[df["is_canceled"] == "NO", "is_canceled"] = "0"

In [ ]:
df.loc[df["is_canceled"] == "YES", "is_canceled"] = "1"

In [ ]:
df["is_canceled"] = df["is_canceled"].astype("int")

In [ ]:
df["is_canceled"].value_counts(dropna=False)

is_canceled
0    71108
1    48282
Name: count, dtype: int64

**Kolona "lead_time":**

In [ ]:
df["lead_time"].value_counts(dropna=False)

lead_time
0         6345
1         3460
2         2069
3         1816
4         1715
          ...
435          1
532          1
371          1
3osam0       1
4šest3       1
Name: count, Length: 479, dtype: int64

In [ ]:
df['lead_time'].unique()

array(['3četiri2', '737', '7', '13', '14', '0', '9', '85', '75', '23',
       '35', '68', '18', '37', '12', '72', '1dva7', '78', '48', '60',
       '77', '99', '118', '95', '96', '69', '45', '40', '15', '36', '43',
       '70', '16', '1nula7', '47', '113', '90', '50', '93', '76', '3',
       '1', '10', '5', '17', '51', '71', '63', '62', '1nula1', '2', '81',
       '3šest8', '3šest4', '3dva4', '79', '21', '1nula9', '1nula2', '4',
       '98', '92', '26', '73', '115', '86', '52', '29', '30', '33', '32',
       '8', '1nula0', '44', '80', '97', '64', '39', '34', '27', '82',
       '94', '110', '111', '84', '66', '1nula4', '28', '258', '112', '65',
       '67', '55', '88', '54', '292', '83', '1nula5', '2osam0', '394',
       '24', '1nula3', '3šest6', '2četiri9', '22', '91', '11', '1nula8',
       '1nula6', '31', '87', '41', '3nula4', '117', '59', '53', '58',
       '116', '42', '3dva1', '38', '56', '49', '317', '6', '57', '19',
       '25', '315', '1dva3', '46', '89', '61', '312', '299', '130', '74',
       '298', '119', '20', '2osam6', '136', '1dva9', '1dva4', '3dva7',
       '131', '4šest0', '1četiri0', '114', '139', '1dva2', '137', '1dva6',
       '1dva0', '1dva8', '135', '150', '1četiri3', '151', '132', '1dva5',
       '157', '1četiri7', '138', '156', '1šest4', '3četiri6', '159',
       '1šest0', '1šest1', '333', '3osam1', '1četiri9', '154', '297',
       '1šest3', '314', '155', '3dva3', '3četiri0', '356', '1četiri2',
       '3dva8', '1četiri4', '336', '2četiri8', '3nula2', '175',
       '3četiri4', '3osam2', '1četiri6', '170', '1šest6', '338', '1šest7',
       '310', '1četiri8', '1šest5', '172', '171', '1četiri5', '1dva1',
       '178', '3nula5', '173', '152', '354', '3četiri7', '158', '1osam5',
       '3četiri9', '1osam3', '352', '177', '2nula0', '192', '3šest1',
       '2nula7', '174', '330', '134', '350', '334', '2osam3', '153',
       '197', '133', '2četiri1', '193', '235', '194', '2šest1', '2šest0',
       '216', '1šest9', '2nula9', '238', '215', '1četiri1', '1osam9',
       '1osam7', '2dva3', '2osam4', '214', '2nula2', '211', '1šest8',
       '230', '2nula3', '1osam8', '232', '7nula9', '219', '1šest2', '196',
       '190', '259', '2dva8', '176', '250', '2nula1', '1osam6', '199',
       '1osam0', '2nula6', '2nula5', '2dva4', '2dva2', '1osam2', '210',
       '275', '212', '2dva9', '218', '2nula8', '191', '1osam1', '179',
       '2četiri6', '255', '2dva6', '2osam8', '253', '252', '2šest2',
       '236', '256', '234', '254', '4šest8', '213', '237', '198', '195',
       '239', '2šest3', '2šest5', '274', '217', '2dva0', '3nula7',
       '2dva1', '233', '257', '2dva7', '276', '2dva5', '2šest4', '311',
       '277', '2nula4', '290', '2šest6', '270', '294', '319', '2osam2',
       '251', '3dva2', '291', '2šest9', '2četiri0', '271', '1osam4',
       '231', '2šest8', '2četiri7', '273', '3nula0', '3nula1', '2šest7',
       '2četiri4', '3nula6', '293', '3nula9', '272', '2četiri2', '295',
       '2osam5', '2četiri3', '3nula8', '398', '3nula3', '2četiri5',
       '4dva4', '279', '331', '2osam1', '339', '434', '357', '3dva5',
       '3dva9', '278', '332', '3četiri3', '3četiri5', '3šest0',
       '3četiri8', '3šest7', '353', '373', '374', '4nula6', '4nula0',
       '3dva6', '379', '399', '316', '3četiri1', '3dva0', '3osam5', '355',
       '3šest3', '358', '296', '4dva2', '390', '335', '370', '376', '375',
       '397', '2osam9', '5četiri2', '4nula3', '3osam3', '3osam4', '359',
       '393', '337', '3šest2', '3šest5', '435', '3osam6', '378', '313',
       '351', '2osam7', '471', '4šest2', '411', '450', '318', '372',
       '371', '454', '532', '4četiri5', '3osam9', '3osam8', '4nula7',
       '4četiri3', '437', '451', '391', '4nula5', '412', '419', '4dva0',
       '4dva6', '433', '4četiri0', '4dva9', '418', '4četiri7', '4šest1',
       '6nula5', '457', '475', '4šest4', '4osam2', '6dva6', '4osam9',
       '496', '5nula3', '510', '517', '5dva4', '531', '538', '5četiri5',
       '552', '559', '5šest6', '573', '5osam0', '5osam7', '594', '6nula1',
       '6nula8', '615', '6dva2', '6dva9', '396', '410', '395', '4dva3',
       '4nula8', '4nula9', '4četiri8', '4šest5', '3osam7', '414', '476',
       '479', '4šest7', '490', '493', '478', '5nula4', '5nula7', '458',
       '518', '5dva1', '377', '4četiri4', '3osam0', '4šest3'],
      dtype=object)

In [ ]:
word_to_digit = {
    "nula": "0",
    "dva": "2",
    "tri": "3",
    "četiri": "4",
    "osam": "8",
    "šest": "6"
}

import re

def decode_mixed_number(x):
    parts = re.findall(r'[0-9]+|[A-Za-zšđčćžŠĐČĆŽ]+', str(x))
    result = ""
    for p in parts:
        if p.isdigit():
            result += p
        else:
            p_lower = p.lower()
            if p_lower in word_to_digit:
                result += word_to_digit[p_lower]
            else:
                result += p
    return result


df["lead_time"] = df["lead_time"].apply(decode_mixed_number)

In [ ]:
df['lead_time'].unique()

array(['342', '737', '7', '13', '14', '0', '9', '85', '75', '23', '35',
       '68', '18', '37', '12', '72', '127', '78', '48', '60', '77', '99',
       '118', '95', '96', '69', '45', '40', '15', '36', '43', '70', '16',
       '107', '47', '113', '90', '50', '93', '76', '3', '1', '10', '5',
       '17', '51', '71', '63', '62', '101', '2', '81', '368', '364',
       '324', '79', '21', '109', '102', '4', '98', '92', '26', '73',
       '115', '86', '52', '29', '30', '33', '32', '8', '100', '44', '80',
       '97', '64', '39', '34', '27', '82', '94', '110', '111', '84', '66',
       '104', '28', '258', '112', '65', '67', '55', '88', '54', '292',
       '83', '105', '280', '394', '24', '103', '366', '249', '22', '91',
       '11', '108', '106', '31', '87', '41', '304', '117', '59', '53',
       '58', '116', '42', '321', '38', '56', '49', '317', '6', '57', '19',
       '25', '315', '123', '46', '89', '61', '312', '299', '130', '74',
       '298', '119', '20', '286', '136', '129', '124', '327', '131',
       '460', '140', '114', '139', '122', '137', '126', '120', '128',
       '135', '150', '143', '151', '132', '125', '157', '147', '138',
       '156', '164', '346', '159', '160', '161', '333', '381', '149',
       '154', '297', '163', '314', '155', '323', '340', '356', '142',
       '328', '144', '336', '248', '302', '175', '344', '382', '146',
       '170', '166', '338', '167', '310', '148', '165', '172', '171',
       '145', '121', '178', '305', '173', '152', '354', '347', '158',
       '185', '349', '183', '352', '177', '200', '192', '361', '207',
       '174', '330', '134', '350', '334', '283', '153', '197', '133',
       '241', '193', '235', '194', '261', '260', '216', '169', '209',
       '238', '215', '141', '189', '187', '223', '284', '214', '202',
       '211', '168', '230', '203', '188', '232', '709', '219', '162',
       '196', '190', '259', '228', '176', '250', '201', '186', '199',
       '180', '206', '205', '224', '222', '182', '210', '275', '212',
       '229', '218', '208', '191', '181', '179', '246', '255', '226',
       '288', '253', '252', '262', '236', '256', '234', '254', '468',
       '213', '237', '198', '195', '239', '263', '265', '274', '217',
       '220', '307', '221', '233', '257', '227', '276', '225', '264',
       '311', '277', '204', '290', '266', '270', '294', '319', '282',
       '251', '322', '291', '269', '240', '271', '184', '231', '268',
       '247', '273', '300', '301', '267', '244', '306', '293', '309',
       '272', '242', '295', '285', '243', '308', '398', '303', '245',
       '424', '279', '331', '281', '339', '434', '357', '325', '329',
       '278', '332', '343', '345', '360', '348', '367', '353', '373',
       '374', '406', '400', '326', '379', '399', '316', '341', '320',
       '385', '355', '363', '358', '296', '422', '390', '335', '370',
       '376', '375', '397', '289', '542', '403', '383', '384', '359',
       '393', '337', '362', '365', '435', '386', '378', '313', '351',
       '287', '471', '462', '411', '450', '318', '372', '371', '454',
       '532', '445', '389', '388', '407', '443', '437', '451', '391',
       '405', '412', '419', '420', '426', '433', '440', '429', '418',
       '447', '461', '605', '457', '475', '464', '482', '626', '489',
       '496', '503', '510', '517', '524', '531', '538', '545', '552',
       '559', '566', '573', '580', '587', '594', '601', '608', '615',
       '622', '629', '396', '410', '395', '423', '408', '409', '448',
       '465', '387', '414', '476', '479', '467', '490', '493', '478',
       '504', '507', '458', '518', '521', '377', '444', '380', '463'],
      dtype=object)

In [ ]:
df["lead_time"] = df["lead_time"].astype("int")

In [ ]:
df["lead_time"].value_counts(dropna=False)

lead_time
0      6345
1      3460
2      2069
3      1816
4      1715
       ...
435       1
532       1
371       1
380       1
463       1
Name: count, Length: 479, dtype: int64

**Kolona "arrival_date_year":**

In [ ]:
df["arrival_date_year"].value_counts(dropna=False)

arrival_date_year
'16    56707
'17    40687
'15    21996
Name: count, dtype: int64

In [ ]:
df['arrival_date_year'].unique()

array(["'15", "'16", "'17"], dtype=object)

In [ ]:
df.loc[df["arrival_date_year"] == "'15", "arrival_date_year"] = "2015"
df.loc[df["arrival_date_year"] == "'16", "arrival_date_year"] = "2016"
df.loc[df["arrival_date_year"] == "'17", "arrival_date_year"] = "2017"

In [ ]:
df["arrival_date_year"] = df["arrival_date_year"].astype("int")

In [ ]:
df["arrival_date_year"].value_counts(dropna=False)

arrival_date_year
2016    56707
2017    40687
2015    21996
Name: count, dtype: int64

**Kolona "arrival_date_month":**

In [ ]:
df["arrival_date_month"].value_counts(dropna=False)

arrival_date_month
August       10233
July          9233
May           8690
October       8201
April         8158
June          8074
September     7739
March         7281
February      5907
November      5022
December      4987
January       4325
8             3644
7             3428
5             3101
10            2959
4             2931
6             2865
9             2769
3             2513
2             2161
12            1793
11            1772
1             1604
Name: count, dtype: int64

In [ ]:
month_map = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

def convert_month(x):
    if isinstance(x, str) and x.capitalize() in month_map.values():
        return x.capitalize()

    try:
        num = int(str(x).strip())
        return month_map.get(num, x)
    except:
        return x

df["arrival_date_month"] = df["arrival_date_month"].apply(convert_month)

In [ ]:
df['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [ ]:
df["arrival_date_month"] = df["arrival_date_month"].astype("string")

In [ ]:
df["arrival_date_month"].value_counts(dropna=False)

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: Int64

**Kolona "arrival_date_week_number":**

In [ ]:
df["arrival_date_week_number"].value_counts(dropna=False)

arrival_date_week_number
3_3    3580
30     3087
32     3045
34     3040
18     2926
2_1    2854
28     2853
1_7    2805
20     2785
2_9    2763
42     2756
3_1    2741
4_1    2699
1_5    2689
2_7    2664
2_5    2663
38     2661
2_3    2621
3_5    2593
3_9    2581
22     2546
24     2498
1_3    2416
16     2405
1_9    2402
40     2397
26     2391
4_3    2352
44     2272
14     2264
3_7    2229
8      2216
36     2167
10     2149
9      2117
7      2109
12     2083
1_1    2070
4_5    1941
5_3    1816
4_9    1782
4_7    1685
46     1574
6      1508
50     1505
48     1504
4      1487
5      1387
3      1319
2      1218
52     1195
1      1047
5_1     933
Name: count, dtype: int64

In [ ]:
df["arrival_date_week_number"] = df["arrival_date_week_number"].astype(str).str.replace("_", "")
df["arrival_date_week_number"] = df["arrival_date_week_number"].astype(int)

In [ ]:
df["arrival_date_week_number"].value_counts(dropna=False)

arrival_date_week_number
33    3580
30    3087
32    3045
34    3040
18    2926
21    2854
28    2853
17    2805
20    2785
29    2763
42    2756
31    2741
41    2699
15    2689
27    2664
25    2663
38    2661
23    2621
35    2593
39    2581
22    2546
24    2498
13    2416
16    2405
19    2402
40    2397
26    2391
43    2352
44    2272
14    2264
37    2229
8     2216
36    2167
10    2149
9     2117
7     2109
12    2083
11    2070
45    1941
53    1816
49    1782
47    1685
46    1574
6     1508
50    1505
48    1504
4     1487
5     1387
3     1319
2     1218
52    1195
1     1047
51     933
Name: count, dtype: int64

**Kolona "arrival_date_day_of_month":**

In [ ]:
df["arrival_date_day_of_month"].value_counts(dropna=False)

arrival_date_day_of_month
17       3647
1        3626
5        3600
19       3419
2        3350
         ...
20+11       4
8+23        3
29+2        3
19+12       3
30+1        2
Name: count, Length: 578, dtype: int64

In [ ]:
df['arrival_date_day_of_month'].unique()

array(['1', '2', '4/2', '1+1', '6/2', '3', '1+2', '2*2', '4', '8/2',
       '1+3', '5', '10/2', '6', '5+1', '12/2', '2*3', '4+2', '3*2', '1+5',
       '7', '4+3', '14/2', '8', '2*4', '16/2', '7+1', '2+6', '6+2', '9',
       '18/2', '6+3', '8+1', '5*2', '20/2', '10', '8+2', '1+9', '2*5',
       '11', '22/2', '4*3', '2*6', '12', '24/2', '6*2', '10+2', '26/2',
       '9+4', '13', '3+10', '12+1', '5+8', '14', '2*7', '10+4', '28/2',
       '30/2', '5*3', '15', '10+5', '4+11', '3*5', '14+2', '16', '8*2',
       '32/2', '4*4', '2*8', '17', '34/2', '4+13', '18', '36/2', '3*6',
       '2+16', '2*9', '19', '6+13', '7+12', '14+5', '40/2', '20', '5*4',
       '15+5', '4*5', '21', '42/2', '11+10', '6+15', '22', '11*2',
       '11+11', '44/2', '6+17', '23', '46/2', '12+11', '24', '48/2',
       '4*6', '6+18', '12*2', '25', '22+3', '6+19', '50/2', '5*5', '21+4',
       '17+8', '4+21', '15+11', '26', '52/2', '2*13', '13*2', '3+24',
       '27', '54/2', '8+19', '10+17', '3*9', '13+14', '9*3', '7*4', '28',
       '7+21', '56/2', '2*14', '29', '18+11', '58/2', '30', '60/2',
       '18+12', '31', '62/2', '11+20', '3+2', '3+3', '6+1', '4+4', '4*2',
       '4+5', '3*3', '9+2', '2+9', '7+4', '5+6', '4+7', '5+7', '6+7',
       '2+11', '7*2', '11+4', '3+12', '8+7', '14+1', '3+13', '9+7',
       '1+16', '9+8', '1+17', '8+10', '9+9', '6*3', '38/2', '9+10', '7*3',
       '2+19', '3*7', '2*11', '7+15', '3+19', '8+15', '22+1', '3*8',
       '10+15', '2+24', '19+7', '21+6', '2+25', '6+22', '4*7', '1+28',
       '11+18', '5+25', '3+28', '23+8', '17+14', '2+1', '3+1', '2+3',
       '2+4', '3+4', '3+5', '1+7', '2+7', '4+6', '6+4', '1+11', '3+9',
       '8+4', '3*4', '1+12', '8+5', '2+13', '7+9', '5+11', '10+6', '2+14',
       '7+10', '4+14', '13+5', '18+1', '14+7', '8*3', '12+12', '2+22',
       '7+18', '18+8', '22+4', '1+26', '17+10', '11+16', '11+17', '3+25',
       '16+13', '16+14', '2+2', '4+1', '1+4', '5+3', '1+8', '7+2', '5+4',
       '5+5', '8+3', '11+6', '3+15', '17+2', '15+4', '18+2', '20+1',
       '1+20', '7+14', '9+13', '12+10', '8+14', '13+11', '11+13', '20+4',
       '16+8', '9+15', '15+10', '25+1', '11+15', '10+16', '20+8', '14*2',
       '2*15', '23+7', '17+13', '21+10', '24+7', '26+5', '13+18', '5+2',
       '2+5', '1+10', '6+5', '11+1', '9+3', '1+13', '13+3', '11+8',
       '12+8', '16+4', '3+17', '9+11', '10+11', '19+2', '8+13', '17+9',
       '8+18', '15+12', '5+23', '2+26', '11+19', '21+9', '7+3', '3+8',
       '5+9', '10+9', '3+16', '1+18', '16+3', '15+7', '13+10', '2*12',
       '14+11', '16+10', '22+5', '6*5', '10*3', '5*6', '7+23', '14+17',
       '13+4', '14+8', '3+20', '2+23', '4+24', '8+20', '14+15', '6+6',
       '4+8', '7+5', '9+6', '2+15', '21+5', '6+20', '6+21', '3+6', '2+10',
       '8+11', '12+7', '1+21', '6*4', '4+20', '15+9', '3+21', '14+10',
       '23+1', '1+24', '21+7', '15+13', '28+2', '20+11', '25+6', '5+26',
       '3+7', '12+4', '11+7', '9*2', '7+11', '10+12', '17+5', '5+17',
       '19+5', '5+19', '1+23', '3+22', '13+12', '16+11', '4+23', '12+16',
       '26+3', '28+1', '3+26', '24+5', '24+6', '8+22', '27+3', '15*2',
       '4+26', '19+11', '9+1', '12+2', '7+7', '6+8', '4+10', '3+11',
       '11+3', '13+1', '12+3', '8+8', '15+2', '6+12', '5+13', '10*2',
       '7+16', '21+3', '23+3', '1+25', '3+23', '10+18', '25+3', '12+18',
       '2+29', '28+3', '7+6', '4+12', '16+1', '12+17', '6+9', '7+8',
       '13+7', '12+9', '13+13', '19+9', '25+4', '25+5', '2+28', '9+22',
       '1+6', '13+6', '17+3', '10+10', '19+3', '20+5', '9+18', '25+2',
       '13+15', '3*10', '13+17', '7+24', '15+16', '9+5', '16+2', '8+12',
       '15+6', '16+5', '2+20', '15+8', '22+2', '29+1', '13+2', '1+15',
       '18+4', '6+16', '13+9', '20+2', '17+7', '18+7', '20+7', '19+8',
       '22+9', '8+9', '16+7', '5+10', '9+14', '20+3', '20+6', '20+9',
       '1+29', '20+10', '22+8', '1+30', '11+5', '24+3', '18+10', '2+27',
       '10+7', '10+8', '15+3', '2+8', '10+3', '4+15', '16+6', '6+23',
       '2+12', '19+1', '6+14', '18+3', '4+18', '5+18', '27+2', '10+19',
       '17+12', '22+7', '21+8', '4+9', '3+18', '16+9', '23+2', '18+13',
       '10+21', '14+3', '6+11', '12+6', '5+14', '21+1', '9+16', '14+13',
       '24+4', '6+24', '10+1', '6+10', '3+14', '8+16', '4+27', '16+15',
       '15+1', '5+12', '2+21', '15+15', '14+9', '1+27', '7+20', '11+14',
       '18+5', '12+5', '3+27', '7+22', '4+16', '11+2', '7+19', '5+15',
       '2+18', '10+14', '5+20', '27+4', '10+20', '19+10', '17+6', '7+17',
       '19+12', '8+21', '9+21', '8+6', '9+12', '17+4', '4+17', '13+8',
       '2*10', '8+17', '1+14', '1+19', '11+12', '27+1', '15+14', '17+1',
       '12+14', '18+9', '26+2', '17+11', '1+22', '14+6', '10+13', '4+19',
       '19+4', '23+5', '14+12', '19+6', '26+1', '4+22', '24+2', '2+17',
       '14+16', '6+25', '12+19', '5+16', '13+16', '5+22', '5+21', '14+4',
       '23+6', '5+24', '26+4', '14+14', '29+2', '11+9', '18+6', '7+13',
       '9+20', '9+17', '23+4', '21+2', '9+19', '22+6', '16+12', '24+1',
       '12+15', '12+13', '8+23', '4+25', '30+1'], dtype=object)

In [ ]:
import re
import operator

ops = {
    "+": operator.add,
    "-": operator.sub,
    "*": operator.mul,
    "/": operator.floordiv
}

def safe_eval(expr):
    expr = str(expr).strip()

    if expr.isdigit():
        return int(expr)

    match = re.fullmatch(r"(\d+)\s*([+\-*/])\s*(\d+)", expr)
    if not match:
        return None

    a, op, b = match.groups()
    a, b = int(a), int(b)

    return ops[op](a, b)

df["arrival_date_day_of_month"] = df["arrival_date_day_of_month"].apply(safe_eval)

df["arrival_date_day_of_month"] = df["arrival_date_day_of_month"].astype(int)

In [ ]:
df['arrival_date_day_of_month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
df["arrival_date_day_of_month"].value_counts(dropna=False)

arrival_date_day_of_month
17    4406
5     4317
15    4196
25    4160
26    4147
9     4096
12    4087
16    4078
2     4055
19    4052
20    4032
18    4002
24    3993
28    3946
8     3921
3     3855
30    3853
6     3833
14    3819
27    3802
21    3767
4     3763
13    3745
7     3665
1     3626
23    3616
11    3599
22    3596
29    3580
10    3575
31    2208
Name: count, dtype: int64

**Kolona "stays_in_weekend_nights":**

In [ ]:
df["stays_in_weekend_nights"].value_counts(dropna=False)

stays_in_weekend_nights
nulica    51998
2         33308
1         30626
4          1855
3          1259
6           153
5            79
8            60
7            19
9            11
10            7
12            5
13            3
16            3
14            2
19            1
18            1
Name: count, dtype: int64

In [ ]:
df.loc[df["stays_in_weekend_nights"] == "nulica", "stays_in_weekend_nights"] = "0"

In [ ]:
df['stays_in_weekend_nights'].unique()

array(['0', '1', '2', '4', '3', '6', '13', '8', '5', '7', '12', '9', '16',
       '18', '19', '10', '14'], dtype=object)

In [ ]:
df["stays_in_weekend_nights"] = df["stays_in_weekend_nights"].astype("int")

In [ ]:
df["stays_in_weekend_nights"].value_counts(dropna=False)

stays_in_weekend_nights
0     51998
2     33308
1     30626
4      1855
3      1259
6       153
5        79
8        60
7        19
9        11
10        7
12        5
13        3
16        3
14        2
19        1
18        1
Name: count, dtype: int64

**Kolona "stays_in_week_nights":**

In [ ]:
df["stays_in_week_nights"].value_counts(dropna=False)

stays_in_week_nights
2^1    33684
2^0    30310
3      22258
5      11077
2^2     9563
0       7645
6       1499
10      1036
7       1029
2^3      656
9        231
15        85
11        56
19        44
12        42
20        41
14        35
13        27
2^4       16
21        15
22         7
18         6
25         6
30         5
17         4
24         3
40         2
33         1
42         1
50         1
2^5        1
26         1
34         1
35         1
41         1
Name: count, dtype: int64

In [ ]:
import re

def decode_power_of_two(x):
    x = str(x).strip()

    if x.isdigit():
        return int(x)

    match = re.fullmatch(r"2\s*\^\s*(\d+)", x)
    if match:
        exp = int(match.group(1))
        return 2 ** exp

    return None

df["stays_in_week_nights"] = df["stays_in_week_nights"].apply(decode_power_of_two)
df["stays_in_week_nights"] = df["stays_in_week_nights"].astype(int)

In [ ]:
df['stays_in_week_nights'].unique()

array([ 0,  1,  2,  3,  4,  5, 10, 11,  8,  6,  7, 15,  9, 12, 33, 20, 14,
       16, 21, 13, 30, 19, 24, 40, 22, 42, 50, 25, 17, 32, 26, 18, 34, 35,
       41])

In [ ]:
df["stays_in_week_nights"].value_counts(dropna=False)

stays_in_week_nights
2     33684
1     30310
3     22258
5     11077
4      9563
0      7645
6      1499
10     1036
7      1029
8       656
9       231
15       85
11       56
19       44
12       42
20       41
14       35
13       27
16       16
21       15
22        7
18        6
25        6
30        5
17        4
24        3
40        2
33        1
42        1
50        1
32        1
26        1
34        1
35        1
41        1
Name: count, dtype: int64

**Kolona "adults":**

In [ ]:
df["adults"].value_counts(dropna=False)

adults
2        89680
samac    23027
3         6202
0          403
4           62
26           5
5            2
27           2
20           2
40           1
55           1
50           1
6            1
10           1
Name: count, dtype: int64

In [ ]:
df.loc[df["adults"] == "samac", "adults"] = "1"

In [ ]:
df["adults"] = df["adults"].astype("int")

In [ ]:
df['adults'].unique()

array([ 2,  1,  3,  4, 40, 26, 50, 27, 55,  0, 20,  6,  5, 10])

In [ ]:
df["adults"].value_counts(dropna=False)

adults
2     89680
1     23027
3      6202
0       403
4        62
26        5
5         2
27        2
20        2
40        1
55        1
50        1
6         1
10        1
Name: count, dtype: int64

**Kolona "children":**

In [ ]:
df["children"].value_counts(dropna=False)

children
childless    110796
1.0            4861
2.0            3652
3.0              76
NaN               4
10.0              1
Name: count, dtype: int64

In [ ]:
df['children'].unique()

array(['childless', '1.0', '2.0', '10.0', '3.0', nan], dtype=object)

In [ ]:
df.loc[df["children"] == "childless", "children"] = "0"

In [ ]:
df["children"] = (df["children"].astype("float").fillna(0).astype(int))

In [ ]:
df['children'].unique()

array([ 0,  1,  2, 10,  3])

In [ ]:
df["children"].value_counts(dropna=False)

children
0     110800
1       4861
2       3652
3         76
10         1
Name: count, dtype: int64

**Kolona "babies":**

In [ ]:
df["babies"].value_counts(dropna=False)

babies
0                   85915
0                   32558
1                     695
1                     205
2                      12
2                       3
10 (natalitet++)        1
9 (natalitet++)         1
Name: count, dtype: int64

In [ ]:
df['babies'].unique()

array([0, 1, 2, '0', '1', '2', '10 (natalitet++)', '9 (natalitet++)'],
      dtype=object)

In [ ]:
import re

def clean_babies(x):
    x = str(x).strip()

    match = re.search(r"\d+", x)
    if match:
        return int(match.group())

    return 0

df["babies"] = df["babies"].apply(clean_babies).astype(int)

In [ ]:
df['babies'].unique()

array([ 0,  1,  2, 10,  9])

In [ ]:
df["babies"].value_counts(dropna=False)

babies
0     118473
1        900
2         15
10         1
9          1
Name: count, dtype: int64

**Kolona "meal":**

In [ ]:
df["meal"].value_counts(dropna=False)

meal
BB                   78015
bed and breakfast    14295
HB                   12324
SC                   10650
half board            2139
Undefined             1169
FB                     682
full board             116
Name: count, dtype: int64

In [ ]:
df['meal'].unique()

array(['BB', 'full board', 'bed and breakfast', 'HB', 'half board', 'FB',
       'SC', 'Undefined'], dtype=object)

In [ ]:
df.loc[df["meal"] == "bed and breakfast", "meal"] = "BB"
df.loc[df["meal"] == "half board", "meal"] = "HB"
df.loc[df["meal"] == "full board", "meal"] = "FB"

In [ ]:
df["meal"].value_counts(dropna=False)

meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

**Kolona "country":**

In [ ]:
df["country"].value_counts(dropna=False)

country
PRT     31902
+351    16688
GBR      7921
FRA      6987
ESP      5688
        ...
MRT         1
KIR         1
SDN         1
ATF         1
SLE         1
Name: count, Length: 205, dtype: int64

In [ ]:
df['country'].unique()

array(['+351', 'PRT', '+44', 'GBR', 'USA', '+34', 'IRL', 'FRA', '+353',
       nan, 'ESP', '+40', 'NOR', 'OMN', 'ARG', 'POL', '+49', '+33', '+1',
       '+32', '+41', 'DEU', 'CN', 'CHE', '+30', 'ITA', '+31', 'DNK',
       '+45', '+7', '+46', '+61', 'EST', 'RUS', 'CZE', '+55', 'BEL',
       'FIN', 'AUS', 'ROU', 'SWE', '+48', 'MOZ', 'BWA', 'LUX', '+86',
       'NLD', '+47', 'BRA', 'SVN', 'ALB', '+91', 'CHN', 'MEX', 'MAR',
       'UKR', 'SMR', 'LVA', 'PRI', 'SRB', 'IND', 'CHL', '+39', 'AUT',
       'BLR', 'LTU', '+968', 'TUR', 'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB',
       'CPV', 'ZWE', 'DZA', 'KOR', 'CRI', '+54', 'HUN', 'ARE', 'TUN',
       'JAM', 'HRV', 'HKG', 'IRN', 'GEO', 'AND', 'GIB', 'URY', 'JEY',
       'CAF', 'CYP', 'GRC', 'COL', 'GGY', 'KWT', 'NGA', '+82', 'MDV',
       'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN', 'PHL', 'SEN',
       'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD', 'MYS', '+52',
       'ARM', 'JPN', '+81', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
       'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
       'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
       'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
       'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
       'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object)

In [ ]:
import re

calling_code_map = {
    "+1": "USA",
    "+7": "RUS",
    "+44": "GBR",
    "+31": "NLD",
    "+30": "GRC",
    "+33": "FRA",
    "+34": "ESP",
    "+39": "ITA",
    "+40": "ROU",
    "+43": "AUT",
    "+45": "DNK",
    "+46": "SWE",
    "+61": "AUS",
    "+55": "BRA",
    "+47": "NOR",
    "+54": "ARG",
    "+48": "POL",
    "+81": "JPN",
    "+82": "KOR",
    "+52": "MEX",
    "+86": "CHN",
    "+91": "IND",
    "+41": "CHE",
    "+49": "DEU",
    "+32": "BEL",
    "+351": "PRT",
    "+353": "IRL",
    "+968": "OMN"
}

def clean_country(val):
    val = str(val).strip()

    if re.fullmatch(r"\+\d+", val):
        return calling_code_map.get(val, None)

    return val

df["country"] = df["country"].apply(clean_country)

In [ ]:
df["country"] = df["country"].replace(["nan", "", "NA", "N/A"], np.nan)

In [ ]:
most_common_country = df["country"].mode(dropna=True)[0]

df["country"] = df["country"].fillna(most_common_country)

In [ ]:
df['country'].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'CHN', 'SVN', 'ALB', 'IND', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
       'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
       'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
       'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
       'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
       'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object)

In [ ]:
df["country"] = df["country"].astype("string")

In [ ]:
df["country"].value_counts(dropna=False)

country
PRT    49078
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
MRT        1
KIR        1
SDN        1
ATF        1
SLE        1
Name: count, Length: 177, dtype: Int64

**Kolona "market_segment":**

In [ ]:
df["market_segment"].value_counts(dropna=False)

market_segment
0n1ine T@        56477
0ff1ine T@/T0    24219
6r0ups           19811
Direct           12606
C0rp0r@te         5295
C0mp1ement@ry      743
@vi@ti0n           237
Undefined            2
Name: count, dtype: int64

In [ ]:
def clean_market_segment(text):
    if pd.isna(text):
        return text

    mapping = {
        "@": "a",
        "6": "g",
        "0": "o",
        "1": "l"
    }

    cleaned = "".join([mapping.get(c, c) for c in text])

    return cleaned.title()

df["market_segment"] = df["market_segment"].apply(clean_market_segment)

In [ ]:
df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online Ta', 'Offline Ta/To',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [ ]:
df.loc[df["market_segment"] == "Online Ta", "market_segment"] = "Online TA"
df.loc[df["market_segment"] == "Offline Ta/To", "market_segment"] = "Offline TA/TO"

In [ ]:
df["market_segment"].value_counts(dropna=False)

market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

**Kolona "distribution_channel":**

In [ ]:
df["distribution_channel"].value_counts(dropna=False)

distribution_channel
tA/TO        6261
tA/tO        6229
Ta/to        6168
ta/to        6165
tA/to        6149
             ...
undEFined       1
undeFINed       1
undefiNeD       1
uNDEfineD       1
uNDEFINeD       1
Name: count, Length: 605, dtype: int64

In [ ]:
df['distribution_channel'].unique()

array(['diREcT', 'dIReCt', 'DiRecT', 'corporatE', 'tA/TO', 'TA/to',
       'DiREcT', 'dIreCt', 'ta/tO', 'tA/To', 'Ta/tO', 'Ta/To', 'TA/tO',
       'Ta/TO', 'CoRpOratE', 'DIREcT', 'Ta/to', 'diRect', 'DirEcT',
       'dirECt', 'ta/to', 'TA/TO', 'dIRect', 'tA/tO', 'diREct', 'DirEct',
       'DIRECt', 'tA/to', 'ta/To', 'dIrECt', 'dirEct', 'ta/TO', 'TA/To',
       'DIReCT', 'DIREct', 'DiRECT', 'DireCt', 'DiRECt', 'DIReCt',
       'dIREcT', 'dIrEcT', 'direct', 'DIrecT', 'DireCT', 'diRecT',
       'DirECT', 'diRECT', 'cORPoRATe', 'cORPOrAte', 'CoRPoRatE',
       'dirEcT', 'direcT', 'DIreCt', 'dIreCT', 'dIrecT', 'DiReCt',
       'diReCt', 'dIrect', 'DIrEcT', 'COrPOraTe', 'dIrEct', 'DIRect',
       'dirECT', 'cOrpOrATE', 'DiReCT', 'CORPoRaTe', 'DIrECt', 'DIreCT',
       'cOrporatE', 'DirecT', 'Direct', 'dIrECT', 'DIRecT', 'diReCT',
       'DirECt', 'DIrEct', 'dIRECT', 'diRECt', 'coRpoRaTE', 'DiREct',
       'dIREct', 'DIrECT', 'CorpOraTe', 'direCT', 'DIrect', 'dIRecT',
       'CoRporate', 'DIRECT', 'cOrPorATE', 'CORPOrATE', 'corpOratE',
       'CORPORaTe', 'COrPOratE', 'corpoRaTe', 'CorpOraTE', 'CorpoRaTe',
       'COrPOrATe', 'COrPorAtE', 'COrpOraTe', 'CORpoRatE', 'COrpOraTE',
       'CorPORate', 'coRpoRAte', 'CoRpoRAtE', 'COrpORate', 'dIRECt',
       'dIReCT', 'CorPOraTE', 'COrPOrate', 'DiRect', 'cOrPORate',
       'direCt', 'corPORATE', 'CoRpOrATe', 'CorpORaTe', 'COrPORATE',
       'coRPOrAte', 'COrpORatE', 'cOrpORaTe', 'CorPOrAtE', 'corPOraTE',
       'CorpORate', 'coRpoRaTe', 'CoRPorAte', 'CORpoRATE', 'corporATe',
       'cOrpORAtE', 'coRPoRAtE', 'COrPORate', 'cORpORATE', 'cORpORate',
       'cORpORatE', 'coRPoRATE', 'CoRpoRate', 'corPORatE', 'CorporAtE',
       'cOrPOraTe', 'coRpORAte', 'CoRPORate', 'CORPoratE', 'coRporAte',
       'CoRpoRatE', 'COrPorate', 'CORPOrAte', 'corPoRATe', 'cOrpORate',
       'cOrPOrATE', 'cOrporATe', 'CorPoraTe', 'cORPORaTe', 'corPoRAtE',
       'COrporAtE', 'cOrpORaTE', 'CORpOrATE', 'CorpoRatE', 'CORpORatE',
       'COrpORAte', 'cORPOraTE', 'cOrPORatE', 'CorpORaTE', 'corpoRATE',
       'coRpORaTe', 'coRpORATe', 'cORporATe', 'CorpoRate', 'coRpOrate',
       'CorpORATE', 'CorPoRATE', 'corpoRATe', 'cORPOraTe', 'coRPORate',
       'corPoRatE', 'cORPoratE', 'CORPORATE', 'CorporATe', 'cORpOrate',
       'cOrPorAtE', 'coRpORaTE', 'CORPORate', 'CoRporaTE', 'CorPoRAtE',
       'coRpoRate', 'CoRpOraTe', 'corPoRaTe', 'CoRPOrATE', 'cOrpOraTe',
       'cORpoRAte', 'cORpOraTE', 'CORpOrAte', 'CorpOratE', 'CORpORate',
       'CoRPoratE', 'coRPORAtE', 'cORPoraTE', 'CORpoRaTE', 'cORPorAte',
       'COrpoRAte', 'CoRPoRATe', 'cOrPOrate', 'cORpORAtE', 'corPORaTe',
       'cOrPOraTE', 'cORpOrAtE', 'CoRpOrAte', 'CoRPORaTE', 'cORpoRAtE',
       'CORpOratE', 'CorPoRATe', 'CoRPoRate', 'CorPoRAte', 'COrporate',
       'cORPoRATE', 'cORPoRatE', 'cOrPORaTE', 'corpOrATe', 'CoRPORatE',
       'corporaTe', 'CORPOratE', 'COrpORAtE', 'CorPoRatE', 'cOrpORAte',
       'cORPorATe', 'CoRpORaTe', 'COrPorAte', 'cORpOrATE', 'cORPoRate',
       'COrPORAtE', 'COrPORATe', 'coRpoRatE', 'CoRpOrate', 'COrpORATE',
       'corpoRatE', 'cORpOraTe', 'COrPoRATE', 'cOrpOrate', 'cORporate',
       'CoRpORate', 'COrpORATe', 'CORPOrATe', 'cORpoRatE', 'corPOratE',
       'CORpOrAtE', 'CORPORAte', 'COrPoRaTE', 'corPorAtE', 'coRPoRate',
       'CORPorATE', 'CorporATE', 'COrporaTe', 'cOrPoRAte', 'COrPoraTE',
       'corPORate', 'cORPoraTe', 'cOrporATE', 'coRpoRATe', 'cOrporAte',
       'CorpoRAte', 'cOrPORATe', 'CorPorAte', 'CORpoRaTe', 'corPoRATE',
       'cORPOratE', 'CoRpoRaTE', 'cORPOrate', 'COrpoRaTe', 'coRpoRAtE',
       'COrpoRate', 'CORPORaTE', 'coRPORAte', 'corporate', 'CoRPorATE',
       'CORPoRaTE', 'CORpoRate', 'coRpOraTE', 'corpORatE', 'cOrpOrAte',
       'CorpOrAte', 'CorPORatE', 'CorPoRaTE', 'cORporaTE', 'COrPORaTE',
       'CorPORAte', 'cORpoRaTE', 'cORPorate', 'CorporAte', 'CorPORAtE',
       'CoRpOraTE', 'cOrporAtE', 'corporAtE', 'coRPoraTe', 'CorpORatE',
       'COrpOrate', 'cOrpOratE', 'COrpoRaTE', 'cORpOrAte', 'CorPORATe',
       'COrPOrAtE', 'CoRPOraTe', 'CorPorate', 'CORporaTe', 'corporaTE',
       'CORPORATe', 'coRpoRATE', 'CORPoRate', 'corPoRaTE', 'cORPOrATe',
       'CORpoRAte', 'CORporaTE', 'CORPorATe', 'CORPorAtE', 'corPOrATe',
       'corPoratE', 'COrPORAte', 'CoRporAtE', 'CorpoRAtE', 'cORPORate',
       'CoRPOrate', 'CORPOrAtE', 'CORpoRATe', 'COrpoRatE', 'COrporaTE',
       'CORporatE', 'CORpOraTE', 'cOrPoraTE', 'coRPoRATe', 'cORpOratE',
       'COrPoRAte', 'corPOrate', 'CoRpORAtE', 'corpORate', 'cOrpoRAte',
       'cORpORaTe', 'CORpORATE', 'cORpORATe', 'CORPORatE', 'coRpOrAte',
       'corpORaTe', 'COrpORaTE', 'cORPORaTE', 'corpORAtE', 'cOrPOrATe',
       'CoRPorATe', 'cORPORAtE', 'CoRPoraTE', 'CorPORaTe', 'CoRPoraTe',
       'CoRPOraTE', 'corpoRAtE', 'cOrpoRATe', 'CORPoRATe', 'COrPOrATE',
       'COrpoRATE', 'CorPoratE', 'cOrpOrAtE', 'CoRpORatE', 'coRPorATE',
       'cOrpoRaTe', 'COrpOrATe', 'CorpoRaTE', 'CorPOrate', 'CorpOrATe',
       'COrporATE', 'COrporATe', 'CorpoRATe', 'cORPoRAte', 'cOrPORATE',
       'cORpOrATe', 'COrPoRAtE', 'corPorate', 'COrPORaTe', 'CORporATE',
       'COrporAte', 'coRPOrATE', 'COrPOraTE', 'cORPoRaTE', 'corpOrate',
       'cOrporaTe', 'corpOraTe', 'cOrPorAte', 'coRPoRatE', 'CORPOrate',
       'COrPoRATe', 'CORpORAte', 'CorPorATE', 'CoRpORATE', 'COrpoRAtE',
       'coRporatE', 'CORPOraTe', 'cOrpOraTE', 'coRpORAtE', 'cORpoRate',
       'corporAte', 'CoRPorate', 'cORPORATe', 'corPOrATE', 'CoRpORaTE',
       'cOrpOrATe', 'cOrporaTE', 'coRPorAte', 'CorpOrAtE', 'coRpOrATe',
       'cOrpoRATE', 'CorporatE', 'coRPorate', 'cOrPOrAtE', 'cOrPoRAtE',
       'cORpORaTE', 'cORporATE', 'COrPORatE', 'CorpOrATE', 'cORpoRaTe',
       'coRPOraTe', 'cORPorAtE', 'COrporatE', 'cOrPorate', 'CORporAtE',
       'cORpoRATE', 'cOrPORAte', 'cOrpORATe', 'CORpORaTe', 'corpOrATE',
       'coRPORATe', 'coRPoraTE', 'CorPOraTe', 'coRPORATE', 'CoRpORATe',
       'CoRporatE', 'CoRPOrAtE', 'COrpoRATe', 'cOrPORAtE', 'cOrpoRate',
       'corPOraTe', 'CoRPOrATe', 'CORporate', 'cOrPoRATE', 'corpoRate',
       'cOrPoratE', 'CORpoRAtE', 'coRporATe', 'CoRPoRAte', 'cORporaTe',
       'corPorATe', 'CorPoraTE', 'coRPORatE', 'CORPoRAte', 'corPoRAte',
       'CorpORAte', 'cORpORAte', 'CorPoRaTe', 'corpoRaTE', 'corpoRAte',
       'cOrpoRAtE', 'CORPoraTE', 'CORPoRatE', 'CoRpoRATe', 'CoRpoRATE',
       'cOrPoRate', 'CorPORaTE', 'CoRPoRATE', 'cORporatE', 'corPORAte',
       'corpOrAtE', 'coRporaTe', 'CORpORAtE', 'corPORaTE', 'coRPoRaTE',
       'cORPorATE', 'CoRpOrAtE', 'cOrPorATe', 'CoRPoRAtE', 'COrPoraTe',
       'corPORAtE', 'CorpORAtE', 'CoRpoRaTe', 'corPorATE', 'coRporAtE',
       'CoRporAte', 'CORpORATe', 'coRpOrAtE', 'corpORATe', 'CorporaTe',
       'CorPOrATE', 'CorPoRate', 'coRpOraTe', 'cORPORAte', 'CoRpORAte',
       'coRporaTE', 'cOrPORaTe', 'CorPOrAte', 'CORpOrATe', 'cORporAtE',
       'cOrPoRaTE', 'coRPoRaTe', 'cORPOrAtE', 'CoRporATE', 'CorPOrATe',
       'corPorAte', 'CoRpOrATE', 'corpOrAte', 'COrpOrATE', 'CoRPOratE',
       'corpOraTE', 'cOrPoRaTe', 'CoRporaTe', 'corPoraTE', 'cORPORATE',
       'coRpORate', 'coRPoRAte', 'CORPOraTE', 'coRPOrate', 'coRPORaTe',
       'coRPorAtE', 'CoRPORATE', 'cORPoRAtE', 'COrPorATE', 'coRPorATe',
       'cOrPOrAte', 'Corporate', 'CoRPoRaTE', 'cOrPOratE', 'corPoraTe',
       'coRPOrATe', 'COrPOrAte', 'cORPOrATE', 'COrPoRate', 'cOrpORATE',
       'CORpORaTE', 'CoRPorAtE', 'COrPoratE', 'CoRporATe', 'corpORAte',
       'uNDEFINeD', 'CORpOrate', 'cORporAte', 'corporATE', 'cOrPoRatE',
       'cOrPoRATe', 'cORPORatE', 'CoRPoRaTe', 'CorporaTE', 'CoRpoRAte',
       'coRPOrAtE', 'corPORATe', 'coRPoratE', 'coRPOratE', 'COrpOrAtE',
       'cOrpORatE', 'CoRPOrAte', 'CORPorate', 'CORporAte', 'coRpORATE',
       'coRporate', 'CORporATe', 'COrpOratE', 'cOrpoRaTE', 'COrpOrAte',
       'corPOrAtE', 'corPOrAte', 'CorPorAtE', 'corpORATE', 'COrPoRaTe',
       'cOrporate', 'cORpoRATe', 'CORPoRAtE', 'coRpORatE', 'CORPoRATE',
       'CorpORATe', 'CORPorAte', 'coRpOratE', 'COrPoRatE', 'coRPOraTE',
       'CorPORATE', 'corpORaTE', 'CorPorATe', 'CoRPORAtE', 'coRPORaTE',
       'cOrpoRatE', 'corPoRate', 'coRpOrATE', 'CoRPORaTe', 'CorpOrate',
       'CORPoraTe', 'coRporATE', 'CorpoRATE', 'cORPoRaTe', 'CorPOratE',
       'CoRPORAte', 'CoRPORATe', 'cOrPoraTe', 'COrPorATe', 'CORpOraTe',
       'COrpORaTe', 'CORPORAtE', 'undeFINed', 'undefiNeD', 'uNDEfineD',
       'undEFined', 'GDs', 'gdS', 'GdS', 'gDs', 'GDS', 'Gds', 'gDS',
       'gds'], dtype=object)

In [ ]:
channel_map = {
    "direct": "Direct",
    "corporate": "Corporate",
    "ta/to": "TA/TO",
    "gds": "GDS",
    "undefined": "Undefined"
}

df["distribution_channel"] = df["distribution_channel"].str.lower()

df["distribution_channel"] = df["distribution_channel"].map(channel_map)

In [ ]:
df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [ ]:
df["distribution_channel"].value_counts(dropna=False)

distribution_channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64

**Kolona "is_repeated_guest":**

In [ ]:
df["is_repeated_guest"].value_counts(dropna=False)

is_repeated_guest
0               104489
novi kolačić     11091
1                 3465
ponovac            345
Name: count, dtype: int64

In [ ]:
df.loc[df["is_repeated_guest"] == "novi kolačić", "is_repeated_guest"] = "0"
df.loc[df["is_repeated_guest"] == "ponovac", "is_repeated_guest"] = "1"

In [ ]:
df["is_repeated_guest"] = df["is_repeated_guest"].astype("int")

In [ ]:
df["is_repeated_guest"].value_counts(dropna=False)

is_repeated_guest
0    115580
1      3810
Name: count, dtype: int64

**Kolona "previous_cancellations":**

In [ ]:
df["previous_cancellations"].value_counts(dropna=False)

previous_cancellations
0             59079
0             53827
1              6024
2               116
24               48
11               35
tri              33
3                32
4                31
1                27
25               25
6                22
5                19
dvašest          16
14               14
19               13
26               10
jedantri          7
jedandevet        6
13                5
21                1
Name: count, dtype: int64

In [ ]:
df['previous_cancellations'].unique()

array(['0', '1', '2', 'tri', 'dvašest', '26', '25', '14', '3', '4', '24',
       '19', 'jedandevet', '5', 0, '21', '6', '13', 'jedantri', '11', 1],
      dtype=object)

In [ ]:
cancellations_map = {
    "tri": 3,
    "jedandevet": 19,
    "dvašest": 26,
    "jedantri": 13
}

df["previous_cancellations"] = df["previous_cancellations"].replace(cancellations_map)

In [ ]:
df["previous_cancellations"] = df["previous_cancellations"].astype("int")

In [ ]:
df['previous_cancellations'].unique()

array([ 0,  1,  2,  3, 26, 25, 14,  4, 24, 19,  5, 21,  6, 13, 11])

In [ ]:
df["previous_cancellations"].value_counts(dropna=False)

previous_cancellations
0     112906
1       6051
2        116
3         65
24        48
11        35
4         31
26        26
25        25
6         22
5         19
19        19
14        14
13        12
21         1
Name: count, dtype: int64

**Kolona "previous_bookings_not_canceled":**

In [ ]:
df["previous_bookings_not_canceled"].value_counts(dropna=False)

previous_bookings_not_canceled
0       76233
0x0     39537
1        1002
0x1       540
2         377
        ...
0x45        1
72          1
71          1
70          1
0x1e        1
Name: count, Length: 105, dtype: int64

In [ ]:
df['previous_bookings_not_canceled'].unique()

array(['0', '0x0', '1', '2', '3', '0x1', '0x2', '0x3', '0x4', '5', '0x5',
       '0x6', '7', '8', '4', '6', '0x7', '9', '10', '11', '12', '0x8',
       '0x9', '0xc', '0xd', '13', '14', '0xf', '16', '0x11', '18', '0x12',
       '0x14', '21', '0x16', '0x17', '24', '25', '27', '0x1c', '0x1d',
       '30', '0xa', '0xb', '0x10', '0x13', '0x15', '23', '0x19', '26',
       '0xe', '15', '17', '19', '20', '22', '28', '31', '0x20', '29',
       '33', '34', '0x23', '36', '37', '38', '0x27', '40', '41', '42',
       '43', '44', '45', '46', '0x2f', '0x30', '48', '49', '50', '0x33',
       '0x34', '53', '54', '55', '0x38', '57', '58', '0x3b', '60', '0x3d',
       '62', '0x3f', '0x40', '65', '66', '0x43', '68', '0x45', '70', '71',
       '72', '0x18', '0x1a', '0x1e', '0x1b'], dtype=object)

In [ ]:
def hex_to_int(val):
    if isinstance(val, str) and val.startswith("0x"):
        return int(val, 16)
    return int(val)

df["previous_bookings_not_canceled"] = df["previous_bookings_not_canceled"].apply(hex_to_int)

In [ ]:
df["previous_bookings_not_canceled"] = df["previous_bookings_not_canceled"].astype("int")

In [ ]:
df['previous_bookings_not_canceled'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 19, 26, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72])

In [ ]:
df["previous_bookings_not_canceled"].value_counts(dropna=False)

previous_bookings_not_canceled
0     115770
1       1542
2        580
3        333
4        229
       ...
68         1
69         1
70         1
71         1
72         1
Name: count, Length: 73, dtype: int64

**Kolona "reserved_room_type":**

In [ ]:
df["reserved_room_type"].value_counts(dropna=False)

reserved_room_type
A     45940
65    40054
D     10157
68     9044
E      3503
69     3032
F      1529
70     1368
G      1166
71      928
B       599
66      519
C       509
67      423
H       327
72      274
P         9
L         6
80        3
Name: count, dtype: int64

In [ ]:
df['reserved_room_type'].unique()

array(['67', '65', 'A', 'C', 'D', '69', '68', 'G', 'E', 'F', '71', '70',
       '72', 'H', 'L', '80', 'P', 'B', '66'], dtype=object)

In [ ]:
def ascii_to_char(val):
    if val.isdigit():
        return chr(int(val))
    return val

df["reserved_room_type"] = df["reserved_room_type"].apply(ascii_to_char)

In [ ]:
df['reserved_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B'], dtype=object)

In [ ]:
df["reserved_room_type"].value_counts(dropna=False)

reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

**Kolona "assigned_room_type":**

In [ ]:
df["assigned_room_type"].value_counts(dropna=False)

assigned_room_type
A    74053
D    16535
0     8787
E     7806
F     3751
C     2375
G     1673
B     1443
6      880
8      720
H      712
K      279
I      235
1      128
P       12
L        1
Name: count, dtype: int64

In [ ]:
room_type_map = {
    "0": "D",
    "6": "G",
    "1": "I",
    "8": "B"
}

df["assigned_room_type"] = df["assigned_room_type"].replace(room_type_map)

In [ ]:
df['assigned_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K'],
      dtype=object)

In [ ]:
df["assigned_room_type"].value_counts(dropna=False)

assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

**Kolona "booking_changes":**

In [ ]:
df["booking_changes"].value_counts(dropna=False)

booking_changes
0             55723
no changes    45591
1             12701
2              3805
3               927
4               376
5               118
6                63
7                31
8                17
9                 8
10                6
14                5
13                5
15                3
17                2
16                2
12                2
11                2
20                1
21                1
18                1
Name: count, dtype: int64

In [ ]:
df.loc[df["booking_changes"] == "no changes", "booking_changes"] = "0"

In [ ]:
df["booking_changes"] = df["booking_changes"].astype("int")

In [ ]:
df['booking_changes'].unique()

array([ 3,  4,  0,  1,  2,  5, 17,  6,  8,  7, 10, 16,  9, 13, 12, 20, 14,
       15, 11, 21, 18])

In [ ]:
df["booking_changes"].value_counts(dropna=False)

booking_changes
0     101314
1      12701
2       3805
3        927
4        376
5        118
6         63
7         31
8         17
9          8
10         6
14         5
13         5
15         3
17         2
16         2
12         2
11         2
20         1
21         1
18         1
Name: count, dtype: int64

**Kolona "deposit_type":**

In [ ]:
df["deposit_type"].value_counts(dropna=False)

deposit_type
No Deposit    43949
1             23221
0             23181
2             22844
Non Refund     6125
Refundable       70
Name: count, dtype: int64

In [ ]:
deposit_map = {
    "0": "No Deposit",
    "1": "Non Refund",
    "2": "Refundable"
}

df["deposit_type"] = df["deposit_type"].replace(deposit_map)
df["deposit_type"] = df["deposit_type"].astype("string")

In [ ]:
df['deposit_type'].unique()

<StringArray>
['No Deposit', 'Non Refund', 'Refundable']
Length: 3, dtype: string

In [ ]:
df["deposit_type"].value_counts(dropna=False)

deposit_type
No Deposit    67130
Non Refund    29346
Refundable    22914
Name: count, dtype: Int64

**Kolona "agent":**

In [ ]:
df["agent"].value_counts(dropna=False)

agent
9.0      19763
NaN      16340
0o11     12198
240.0     8693
0o360     5229
         ...
341.0        1
346.0        1
283.0        1
0o734        1
304.0        1
Name: count, Length: 596, dtype: int64

In [ ]:
df = df.drop(columns=["agent"])

**Kolona "company":**

In [ ]:
df["company"].value_counts(dropna=False)

company
NaN                       112593
****                         659
**|**|***                    567
40.0                         269
****|*****                   266
                           ...
351.0                          1
417.0                          1
243.0                          1
****|*******|*********         1
****|****|******               1
Name: count, Length: 528, dtype: int64

In [ ]:
df['company'].unique()

array([nan, '*|*', '110.0', '113.0', '270.0', '*|*******|********',
       '**|****', '*|*****|****', '178.0', '*|****|****', '***|*******',
       '307.0', '**|******|********', '268.0', '154.0', '*****|*********',
       '204.0', '***|*|**', '***|*|********', '*********|****',
       '*|*******|****', '274.0', '174.0', '*|*********|*****',
       '**|**|***', '223.0', '317.0', '***|*|*******', '**|********|*',
       '*|*|********', '281.0', '*****|***', '**|********|******', '*|**',
       '47.0', '***|**|****', '324.0', '***|****|**', '342.0',
       '***|*******|***', '286.0', '371.0', '383.0', '********|******',
       '********|**', '82.0', '218.0', '********|********', '*|*|***',
       '***|*', '31.0', '****|*******', '***|*********|*******', '392.0',
       '405.0', '***|***|*', '367.0', '***|******|*******', '20.0', '**',
       '********|***', '83.0', '****|*|******', '*****|*', '53.0',
       '395.0', '***|****', '********|****', '***|******', '****|*****',
       '394.0', '***|*********|****', '94.0', '457.0', '382.0',
       '**|*******', '461.0', '478.0', '***|********|******', '*|*|**',
       '112.0', '486.0', '****|**|*', '*********', '***|********',
       '308.0', '*|***|*****', '**|**|****', '*****|****',
       '**|******|*********', '356.0', '****|*********|********', '498.0',
       '***|*********', '195.0', '*****|*|***', '**|***', '**|******|***',
       '****|*******|*******', '477.0', '521.0', '135.0',
       '*|******|*********', '169.0', '*****|*|*****', '445.0', '337.0',
       '**|*****|*', '****|**|********', '**|*********|**',
       '***|********|********', '*|***', '250.0', '***|*****|*****',
       '**|*****|****', '543.0', '531.0', '*****|**|********', '62.0',
       '******|**', '120.0', '****|**', '81.0', '********|*', '116.0',
       '*|*|******', '103.0', '144.0', '*|******', '*********|**', '61.0',
       '***|*****|******', '12.0', '****|*****|*******', '501.0',
       '*|******|*****', '**|*********|*', '291.0', '292.0', '86.0',
       '**|*********', '290.0', '9.0', '****|***', '325.0', '192.0',
       '*|*********|**', '108.0', '200.0', '51.0', '34.0', '224.0',
       '269.0', '****|******|*****', '465.0', '**|********|*******',
       '287.0', '**|*********|*******', '297.0', '****|*********',
       '482.0', '**|********|**', '437.0', '**|**|*****',
       '***|**|*********', '**|*******|**', '**|********',
       '*******|*******', '****|********|**', '42.0', '***|***|********',
       '338.0', '*|********', '72.0', '*******|**', '246.0', '28.0',
       '***|*|*********', '**|*******|****', '*|****|******',
       '*|*****|*********', '380.0', '***|**|***', '92.0', '511.0',
       '407.0', '***|**|*****', '88.0', '***|*******|*',
       '**|*******|********', '***|***|*******', '16.0', '********',
       '***|*********|*********', '399.0', '*|****', '137.0',
       '*|***|*******', '343.0', '***|****|******', '346.0',
       '***|****|*******', '***|****|***', '***|****|*********',
       '**|********|*********', '289.0', '***|*****|*', '355.0', '353.0',
       '*********|*********', '99.0', '**|*****', '***|*****|********',
       '***|******|*', '390.0', '362.0', '366.0', '***|*******|**',
       '365.0', '**|*******|*******', '109.0', '207.0', '358.0',
       '***|*******|*******', '43.0', '379.0', '***|*******|*********',
       '22.0', '***|*******|********', '378.0', '***|***', '**|**',
       '***|******|****', '***|******|******', '360.0', '****|*',
       '**|***|**', '232.0', '**|*****|*****', '384.0',
       '***|********|****', '167.0', '*|******|*******', '**|*|**',
       '514.0', '***|*********|*', '400.0', '***|*******|******', '165.0',
       '402.0', '******|*', '***|*********|******', '331.0', '***|**',
       '***|*********|********', '6.0', '263.0', '370.0', '*****|*|****',
       '397.0', '369.0', '***|******|*********', '409.0', '251.0',
       '168.0', '323.0', '428.0', '***|********|**', '****|********',
       '****|*|***', '148.0', '*|****|********', '*', '333.0',
       '****|*|*********', '****|*|*****', '424.0', '425.0',
       '****|**|***', '****|**|**', '***|*********|*****', '435.0',
       '****|***|*********', '****|****|**', '****|****|*****',
       '****|****|********', '****|****|***', '443.0', '454.0', '444.0',
       '****|****|****', '*****|**', '****|*****|*********',
       '****|*****|********', '****|*****|******', '456.0',
       '***|*****|***', '254.0', '460.0', '****|******', '447.0',
       '****|****|*******', '*|******|********', '470.0', '302.0',
       '255.0', '466.0', '364.0', '****|********|****', '*|********|****',
       '****|********|*****', '****|********|*******', '****|*********|*',
       '490.0', '****|*********|****', '494.0', '388.0', '193.0',
       '*****|*|******', '****|*********|******', '146.0',
       '****|*********|*********', '29.0', '272.0', '*******|********',
       '484.0', '225.0', '130.0', '159.0', '520.0', '*****|*******',
       '507.0', '*****|******', '515.0', '459.0', '512.0', '*****|*|**',
       '*|**|******', '*****|*|*', '64.0', '242.0', '*****|*|********',
       '*****|**|*', '*****|**|***', '523.0', '539.0',
       '*****|***|*********', '****|***|*******', '*****|***|****',
       '****|***|******', '436.0', '*****|**|*****', '525.0',
       '*****|****|*', '****', '****|*****|*****', '40.0', '38.0', '45.0',
       '49.0', '48.0', '******|*******', '******|********', '68.0',
       '65.0', '*********|*', '37.0', '67.0', '*|*******|*********',
       '209.0', '**|*|*********', '**|**|*', '227.0', '153.0', '186.0',
       '*|*****|***', '**|*|********', '179.0', '78.0', '**|*****|***',
       '202.0', '**|*|******', '**|*******|*****', '**|***|***', '233.0',
       '277.0', '309.0', '***|**|*', '*********|***', '316.0',
       '********|*****', '107.0', '***|*****', '350.0',
       '**|*******|*********', '***|***|****', '348.0',
       '***|****|********', '279.0', '***|******|*****', '**|****|**',
       '****|***|*****', '*|*****', '*******|***', '***|********|*****',
       '385.0', '****|*|********', '418.0', '197.0',
       '*|*********|*******', '91.0', '450.0', '452.0', '****|*****|**',
       '150.0', '****|******|******', '*|*|*****', '280.0', '46.0',
       '*******|******', '*********|******', '100.0', '105.0', '122.0',
       '*|**|**', '*|***|*********', '*|****|**', '*|**|*******', '127.0',
       '143.0', '*|****|***', '*|*******', '*|****|*********',
       '*|******|***', '160.0', '*|********|******', '163.0',
       '**|***|********', '238.0', '219.0', '183.0', '*|********|***',
       '**|**|**', '203.0', '*|********|*****', '**|*|*******', '217.0',
       '180.0', '215.0', '**|*|*****', '*|*********|***', '185.0',
       '**|*|***', '237.0', '222.0', '230.0', '234.0', '216.0', '221.0',
       '**|**|*******', '**|****|******', '**|****|*****',
       '*|*****|********', '258.0', '**|*****|*********', '**|******',
       '260.0', '411.0', '****|*|*', '**|*****|*******', '271.0',
       '**|*******|*', '275.0', '210.0', '**|*******|***', '*******|*',
       '71.0', '**|********|****', '301.0', '305.0', '**|*********|***',
       '**|******|****', '***|*|*', '***|*|***', '**|********|********',
       '***|*|****', '332.0', '***|***|**', '***|***|***', '***|****|*',
       '352.0', '351.0', '***|******|**', '**|****|***', '372.0', '319.0',
       '377.0', '***|********|***', '368.0', '***|*********|***', '341.0',
       '*|***|**', '408.0', '220.0', '****|*|**', '410.0',
       '****|**|******', '396.0', '417.0', '243.0', '****|**|*********',
       '433.0', '****|****|******', '14.0', '****|**|****',
       '***|*****|*******', '****|*******|*********',
       '****|*******|********', '485.0', '****|********|***',
       '****|********|*********', '229.0', '****|********|******',
       '439.0', '****|********|*', '****|*********|*******',
       '****|*****|*', '492.0'], dtype=object)

In [ ]:
df = df.drop(columns=["company"])

**Kolona "days_in_waiting_list":**

In [ ]:
df["days_in_waiting_list"].value_counts(dropna=False)

days_in_waiting_list
0 mjeseci i 0 dana     63660
0                      52032
1 mjeseci i 9 dana       125
39                       102
1 mjeseci i 28 dana       84
                       ...
3 mjeseci i 2 dana         1
2 mjeseci i 14 dana        1
5 mjeseci i 17 dana        1
0 mjeseci i 13 dana        1
1 mjeseci i 6 dana         1
Name: count, Length: 231, dtype: int64

In [ ]:
df['days_in_waiting_list'].unique()

array(['0 mjeseci i 0 dana', '0', '50', '47', '1 mjeseci i 17 dana',
       '2 mjeseci i 5 dana', '65', '4 mjeseci i 2 dana', '122',
       '2 mjeseci i 15 dana', '75', '3 mjeseci i 11 dana', '101',
       '5 mjeseci i 0 dana', '150', '125', '4 mjeseci i 5 dana', '14',
       '60', '1 mjeseci i 4 dana', '1 mjeseci i 20 dana', '100', '22',
       '121', '61', '39', '5', '0 mjeseci i 5 dana', '0 mjeseci i 1 dana',
       '0 mjeseci i 8 dana', '1', '3 mjeseci i 17 dana', '43',
       '1 mjeseci i 22 dana', '2', '0 mjeseci i 11 dana', '142', '116',
       '13', '44', '3 mjeseci i 7 dana', '97', '2 mjeseci i 23 dana', '4',
       '0 mjeseci i 14 dana', '0 mjeseci i 4 dana', '113',
       '3 mjeseci i 23 dana', '18', '0 mjeseci i 20 dana', '185',
       '6 mjeseci i 5 dana', '107', '93', '109', '34', '6',
       '0 mjeseci i 6 dana', '2 mjeseci i 0 dana', '1 mjeseci i 7 dana',
       '1 mjeseci i 13 dana', '105', '3 mjeseci i 10 dana',
       '5 mjeseci i 4 dana', '64', '2 mjeseci i 4 dana',
       '4 mjeseci i 1 dana', '8', '2 mjeseci i 1 dana', '20',
       '3 mjeseci i 9 dana', '1 mjeseci i 8 dana', '38',
       '1 mjeseci i 18 dana', '48', '33', '1 mjeseci i 3 dana',
       '2 mjeseci i 17 dana', '77', '0 mjeseci i 21 dana', '21', '80',
       '2 mjeseci i 20 dana', '59', '1 mjeseci i 29 dana', '40',
       '1 mjeseci i 10 dana', '1 mjeseci i 28 dana', '58',
       '2 mjeseci i 29 dana', '1 mjeseci i 23 dana', '53',
       '1 mjeseci i 19 dana', '49', '2 mjeseci i 9 dana', '69', '87',
       '2 mjeseci i 27 dana', '3 mjeseci i 1 dana', '91',
       '1 mjeseci i 27 dana', '57', '99', '111', '3 mjeseci i 21 dana',
       '2 mjeseci i 19 dana', '79', '98', '3 mjeseci i 8 dana',
       '2 mjeseci i 25 dana', '85', '63', '2 mjeseci i 3 dana', '15',
       '0 mjeseci i 15 dana', '0 mjeseci i 3 dana', '3',
       '3 mjeseci i 3 dana', '41', '1 mjeseci i 11 dana',
       '7 mjeseci i 14 dana', '224', '31', '1 mjeseci i 9 dana',
       '1 mjeseci i 26 dana', '56', '187', '6 mjeseci i 7 dana', '176',
       '5 mjeseci i 26 dana', '71', '2 mjeseci i 11 dana',
       '1 mjeseci i 25 dana', '55', '3 mjeseci i 6 dana', '236',
       '8 mjeseci i 19 dana', '96', '7 mjeseci i 26 dana', '259',
       '6 mjeseci i 27 dana', '207', '7 mjeseci i 5 dana', '215', '160',
       '5 mjeseci i 10 dana', '4 mjeseci i 0 dana', '120',
       '1 mjeseci i 0 dana', '1 mjeseci i 1 dana', '32', '27', '62',
       '2 mjeseci i 2 dana', '24', '3 mjeseci i 18 dana', '108',
       '4 mjeseci i 27 dana', '147', '1 mjeseci i 2 dana', '379',
       '12 mjeseci i 19 dana', '70', '2 mjeseci i 10 dana',
       '1 mjeseci i 5 dana', '35', '178', '5 mjeseci i 28 dana',
       '11 mjeseci i 0 dana', '330', '7 mjeseci i 13 dana', '223',
       '5 mjeseci i 24 dana', '174', '0 mjeseci i 24 dana', '162',
       '5 mjeseci i 12 dana', '13 mjeseci i 1 dana', '391',
       '2 mjeseci i 8 dana', '68', '11', '193', '10', '76',
       '2 mjeseci i 16 dana', '0 mjeseci i 16 dana', '16',
       '0 mjeseci i 22 dana', '0 mjeseci i 28 dana', '9',
       '0 mjeseci i 9 dana', '5 mjeseci i 15 dana', '1 mjeseci i 14 dana',
       '0 mjeseci i 17 dana', '0 mjeseci i 25 dana', '46',
       '1 mjeseci i 16 dana', '0 mjeseci i 7 dana', '28',
       '0 mjeseci i 27 dana', '84', '5 mjeseci i 25 dana',
       '6 mjeseci i 3 dana', '0 mjeseci i 18 dana', '0 mjeseci i 10 dana',
       '23', '117', '12', '0 mjeseci i 23 dana', '54', '26',
       '0 mjeseci i 26 dana', '73', '17', '1 mjeseci i 15 dana', '45',
       '0 mjeseci i 19 dana', '19', '1 mjeseci i 12 dana', '42', '25',
       '2 mjeseci i 12 dana', '0 mjeseci i 12 dana', '0 mjeseci i 2 dana',
       '2 mjeseci i 21 dana', '3 mjeseci i 2 dana', '2 mjeseci i 14 dana',
       '5 mjeseci i 17 dana', '0 mjeseci i 13 dana', '1 mjeseci i 6 dana'],
      dtype=object)

In [ ]:
import re
def parse_waiting(val):
    if pd.isna(val):
        return np.nan

    if re.fullmatch(r"\d+", str(val).strip()):
        return int(val)

    m = re.match(r"(\d+)\s+mjeseci\s+i\s+(\d+)\s+dana", str(val))
    if m:
        months = int(m.group(1))
        days = int(m.group(2))
        return months * 30 + days

    return np.nan

df["days_in_waiting_list"] = df["days_in_waiting_list"].apply(parse_waiting)
df["days_in_waiting_list"] = df["days_in_waiting_list"].astype("int")

In [ ]:
df['days_in_waiting_list'].unique()

array([  0,  50,  47,  65, 122,  75, 101, 150, 125,  14,  60,  34, 100,
        22, 121,  61,  39,   5,   1,   8, 107,  43,  52,   2,  11, 142,
       116,  13,  44,  97,  83,   4, 113,  18,  20, 185,  93, 109,   6,
        37, 105, 154,  64,  99,  38,  48,  33,  77,  21,  80,  59,  40,
        58,  89,  53,  49,  69,  87,  91,  57, 111,  79,  98,  85,  63,
        15,   3,  41, 224,  31,  56, 187, 176,  71,  55,  96, 236, 259,
       207, 215, 160, 120,  30,  32,  27,  62,  24, 108, 147, 379,  70,
        35, 178, 330, 223, 174, 162, 391,  68, 193,  10,  76,  16,  28,
         9, 165,  17,  25,  46,   7,  84, 175, 183,  23, 117,  12,  54,
        26,  73,  45,  19,  42,  72,  81,  92,  74, 167,  36])

In [ ]:
df["days_in_waiting_list"].value_counts(dropna=False)

days_in_waiting_list
0      115692
39        227
58        164
44        141
31        127
        ...
81          1
92          1
74          1
167         1
36          1
Name: count, Length: 128, dtype: int64

**Kolona "customer_type":**

In [ ]:
df["customer_type"].value_counts(dropna=False)

customer_type
Transient          59176
Transient-Party    16591
Contract            2703
Group                395
trANSieNt             83
                   ...
TransIENT-PArTY        1
TRAnSIEnt-PaRtY        1
trANsIEnt-ParTY        1
TRAnsienT-PARty        1
TrAnsieNt-PArTY        1
Name: count, Length: 7475, dtype: int64

In [ ]:
def clean_customer_type(val):
    if pd.isna(val):
        return val

    val = str(val).lower()

    parts = val.split("-")

    parts = [p.capitalize() for p in parts]

    return "-".join(parts)

df["customer_type"] = df["customer_type"].apply(clean_customer_type)

In [ ]:
df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [ ]:
df["customer_type"].value_counts(dropna=False)

customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

**Kolona "adr":**

In [ ]:
df["adr"].value_counts(dropna=False)

adr
62.0        1966
62+0.0      1788
75.0        1445
90.0        1322
65.0        1296
            ...
95.12          1
173.73         1
113+0.98       1
116+0.99       1
155.61         1
Name: count, Length: 12549, dtype: int64

In [ ]:
df['adr'].unique()

array(['0+0.0', '75.0', '75+0.0', ..., '96+0.14', '225+0.43', '157.71'],
      dtype=object)

In [ ]:
def clean_adr(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip()
    try:
      if "+" in val:
        try:
            parts = val.split("+")
            nums = [float(p) for p in parts]
            return sum(nums)
        except:
            return np.nan

      if float(val).is_integer():
            return int(val)
      return float(val)
    except:
        return val

df["adr"] = df["adr"].apply(clean_adr)

In [ ]:
df["adr"].value_counts(dropna=False)

adr
62.0      1966
62.0      1788
75.0      1445
90.0      1322
65.0      1296
          ...
95.12        1
173.73       1
116.99       1
92.21        1
275.9        1
Name: count, Length: 9203, dtype: int64

**Kolona "required_car_parking_spaces":**

In [ ]:
df["required_car_parking_spaces"].value_counts(dropna=False)

required_car_parking_spaces
0                   70525
nemam auto :(       41449
1                    4672
imam jedan autic     2711
2                      28
3                       3
8                       2
Name: count, dtype: int64

In [ ]:
df.loc[df["required_car_parking_spaces"] == "nemam auto :(", "required_car_parking_spaces"] = "0"

In [ ]:
df.loc[df["required_car_parking_spaces"] == "imam jedan autic", "required_car_parking_spaces"] = "1"

In [ ]:
df['required_car_parking_spaces'].unique()

array(['0', '1', '2', '8', '3'], dtype=object)

In [ ]:
df["required_car_parking_spaces"] = df["required_car_parking_spaces"].astype("int")

In [ ]:
df["required_car_parking_spaces"].value_counts(dropna=False)

required_car_parking_spaces
0    111974
1      7383
2        28
3         3
8         2
Name: count, dtype: int64

**Kolona "total_of_special_requests":**

In [ ]:
df["total_of_special_requests"].value_counts(dropna=False)

total_of_special_requests
nula          45044
0             25274
nedovoljan    21226
1             12000
dovoljan       8311
2              4658
dobar          1572
3               925
vrlo dobar      232
4               108
odlican          25
5                15
Name: count, dtype: int64

In [ ]:
grades_mapping = {
    'nula': 0,
    'nedovoljan': 1,
    'dovoljan': 2,
    'dobar': 3,
    'vrlo dobar': 4,
    'odlican': 5,
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5
}

df['total_of_special_requests'] = df['total_of_special_requests'].replace(grades_mapping)

/tmp/ipython-input-1237378472.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['total_of_special_requests'] = df['total_of_special_requests'].replace(grades_mapping)

In [ ]:
df['total_od_special_requests'] = df['total_of_special_requests'].astype(int)

In [ ]:
df['total_of_special_requests'].unique()

array([0, 1, 3, 2, 4, 5])

In [ ]:
df["total_of_special_requests"].value_counts(dropna=False)

total_of_special_requests
0    70318
1    33226
2    12969
3     2497
4      340
5       40
Name: count, dtype: int64

**Kolona "reservation_status":**

In [ ]:
df["reservation_status"].value_counts(dropna=False)

reservation_status
0000         39099
Check-Out    36067
0001         22354
Canceled     20663
0010           630
No-Show        577
Name: count, dtype: int64

In [ ]:
df['reservation_status'].unique()

array(['0000', 'Check-Out', '0001', 'Canceled', '0010', 'No-Show'],
      dtype=object)

In [ ]:
reservations = {
    '0000': "Check-Out",
    '0001': "Canceled",
    '0010': "No-Show"
}

df['reservation_status'] = df['reservation_status'].replace(reservations)
df["reservation_status"] = df["reservation_status"].astype("string")

In [ ]:
df["reservation_status"].value_counts(dropna=False)

reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: Int64

**Kolona "reservation_status_date":**

In [ ]:
df["reservation_status_date"].value_counts(dropna=False)

reservation_status_date
21/10/2015    942
2015-10-21    519
25/11/2016    512
06/07/2015    499
01/01/2015    488
             ...
2015-03-23      1
2015-04-27      1
2015-06-10      1
2015-03-29      1
2015-04-14      1
Name: count, Length: 1804, dtype: int64

In [ ]:
import pandas as pd
import re

def fix_reservation_date(val):
    if pd.isna(val):
        return val

    val = str(val).strip()

    if re.match(r"^\d{2}/\d{2}/\d{4}$", val):
        try:
            return pd.to_datetime(val, format="%d/%m/%Y").strftime("%Y-%m-%d")
        except:
            return val

    if re.match(r"^\d{4}-\d{2}-\d{2}$", val):
        return val

    return val

df["reservation_status_date"] = df["reservation_status_date"].apply(fix_reservation_date)

In [ ]:
df["reservation_status_date"].value_counts(dropna=False)

reservation_status_date
2015-10-21    1461
2015-07-06     805
2016-11-25     790
2015-01-01     763
2016-01-18     625
              ...
2015-02-26       1
2015-03-18       1
2015-03-12       1
2015-03-11       1
2015-06-14       1
Name: count, Length: 926, dtype: int64

In [ ]:
df.to_csv("/content/hotel_ociscen.csv", index=False)

In [ ]:
df.to_csv("/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv", index=False)

In [ ]:
#greškom u kucanju dodana nova kolona
df1 = pd.read_csv('/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv')

In [ ]:
df1 = df1.drop(columns=["total_od_special_requests"])

In [ ]:
df1.to_csv("/content/drive/MyDrive/MU Projekat/hotel_ociscen.csv", index=False)